# Generated by Django 3.2.9 on 2021-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('department', models.CharField(max_length=255, null=True, verbose_name='Отдел')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Пароль')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
